development:
  dialect: mysql
  dir: db/migrations
  datasource: root:wN.=f2m,$,#GfJ[e@tcp(127.0.0.1)/waroka?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
production:
  dialect: mysql
  dir: db/migrations
  datasource: root:wN.=f2m,$,#GfJ[e@tcp(127.0.0.1)/waroka?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true