// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"waroka/controllers"
	"waroka/controllers/room"
	"waroka/repository"
	"waroka/services"
)

// Injectors from providers.go:

func InitializeUserController(db *gorm.DB) *controllers.UserController {
	iUserRepository := repository.NewUserRepository(db)
	iUserService := services.NewUserService(iUserRepository)
	iAuthService := services.NewAuthService(iUserRepository)
	userController := controllers.NewUserController(iUserService, iAuthService)
	return userController
}

func InitializeAuthController(db *gorm.DB) *controllers.AuthController {
	iUserRepository := repository.NewUserRepository(db)
	iUserService := services.NewUserService(iUserRepository)
	iAuthService := services.NewAuthService(iUserRepository)
	authController := controllers.NewAuthController(iUserService, iAuthService)
	return authController
}

func InitializeRoomController(db *gorm.DB) *controllers.RoomController {
	iUserRepository := repository.NewUserRepository(db)
	iUserService := services.NewUserService(iUserRepository)
	iRoomRepository := repository.NewRoomRepository(db)
	iRoomService := services.NewRoomService(iRoomRepository)
	iPaymentDetailRepository := repository.NewPaymentDetailRepository(db)
	iPaymentDestinationRepository := repository.NewPaymentDestinationRepository(db)
	iPaymentService := services.NewPaymentService(iPaymentDetailRepository, iPaymentDestinationRepository, iRoomRepository, iUserRepository)
	roomController := controllers.NewRoomController(iUserService, iRoomService, iPaymentService)
	return roomController
}

func InitializePaymentController(db *gorm.DB) *room.PaymentController {
	iUserRepository := repository.NewUserRepository(db)
	iUserService := services.NewUserService(iUserRepository)
	iRoomRepository := repository.NewRoomRepository(db)
	iRoomService := services.NewRoomService(iRoomRepository)
	iPaymentDetailRepository := repository.NewPaymentDetailRepository(db)
	iPaymentDestinationRepository := repository.NewPaymentDestinationRepository(db)
	iPaymentService := services.NewPaymentService(iPaymentDetailRepository, iPaymentDestinationRepository, iRoomRepository, iUserRepository)
	paymentController := room.NewPaymentController(iUserService, iRoomService, iPaymentService)
	return paymentController
}
