name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Build for Linux
        run: |
          export GOOS=linux GOARCH=amd64 
          go install github.com/rubenv/sql-migrate/...@latest
          sql-migrate down -env=production
          sql-migrate up -env=production  
          CGO_ENABLED=0 go build -o ./waroka -ldflags "-s -w"

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_waroka
          chmod 600 ~/.ssh/id_waroka
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy to Server
        run: |
          scp -i ~/.ssh/id_waroka ./waroka waroka@${{ secrets.SERVER_HOST }}:/home/waroka/
          ssh -i ~/.ssh/id_waroka waroka@${{ secrets.SERVER_HOST }} "chmod +x /home/waroka/waroka && sudo systemctl restart waroka.service && sudo systemctl status waroka.service && exit"
          rm -rf ~/.ssh/id_waroka
